### ISSUE TITLE
[TO DO] ~21/09/05까지 끝내야 할 목록

### ISSUE THREAD

**Issue by minsungbyun** [minsungbyun/happy-share#17]
- [x] - 개인봉사 반려했을 때 반려 안한 false것도 목록에 나타남(수정필요)
- [x] - 회원가입 똑같은 아이디로 가입되는 것 막기
- [x] - 아이디 찾기 - 이메일로 찾을때 오류발생 해결
- [x] - 명령어 입력시 sysout으로 표시(기능구현 실행했을 때)
- [x] ~~서치기능 추가~~
- [x] ~~이메일도 골뱅이 없으면 처리 예외처리 부분~~
- [x] - 이미 등록되어 있는 아이디로 회원가입하면 중복됩니다라고 표시한다.
- [x] ~~App - static import 적용~~
- [x] ~~비트연산자 활용해서 권한설정~~
- [x] ~~command design pattern으로 쪼개기(아직안된것)~~
- [x] ~~권한 설정 관련 Menu , MenuGroup 수정~~
- [x] - [함께해요] 개인봉사신청 오류가 났는데 신청이 완료되었다는 메세지가 뜸

~~- [ ] - 소개페이지  ex) 저희는 xxxxx 를 지향합니다.~~

**Comment by wejunguk** [comment]
command design pattern으로 쪼개기 완료
