### ISSUE TITLE
[TO DO]21/09/04  권한설정(비트연산자 활용)

### ISSUE THREAD

**Issue by Leejiho-940915** [minsungbyun/happy-share#18]
App클래스 재정비

 권한 설정
-  ACCESS_LOGOUT = 0x01; // 비회원
-   ACCESS_MEMBER = 0x02; // 개인회원
-   ACCESS_ORG = 0x04;    // 기관회원
-   ACCESS_ADMIN = 0x08;  // 관리자

**Comment by minsungbyun** [comment]
해결완료
